import "./globals.css";
import type { Metadata } from "next";
import { Inter, Commissioner } from "next/font/google";
import { QuizProvider } from "./providers/QuizProvider";
import classNames from "classnames";

const inter = Inter({ subsets: ["latin"] });
const commissioner = Commissioner({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={classNames(commissioner.className)}>
        <QuizProvider>{children}</QuizProvider>
      </body>
    </html>
  );
}
